---
deployment:
  tasks:
    - /bin/cp EN_solutions.html /home/ttsmcomm/public_html/
    - /bin/cp ES_solutions.html /home/ttsmcomm/public_html/
    - /bin/cp html/solutions/EN_solutionsMenu.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_solutionsMenu.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_AutomatedMeasurementAndInspection.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_AutomatedMeasurementAndInspection.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_AutomaticMeasuringSolutionAutomatic.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_AutomaticMeasuringSolutionAutomatic.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/link/EN_AutomatedMeasurementAndInspection_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_AutomatedMeasurementAndInspection_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_AutomaticMeasuringSolutionAutomatic_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_AutomaticMeasuringSolutionAutomatic_link.html /home/ttsmcomm/public_html/html/solutions/link/