---
deployment:
  tasks:
    - /bin/cp TTSM/system_v2/js/sharepoint/systemPageCtrl.js /home/ttsmcomm/public_html/TTSM/system_v2/js/sharepoint/
    - /bin/cp TTSM/system_v2/html/util/modal/modal_sharepoint_textarea.html /home/ttsmcomm/public_html/TTSM/system_v2/html/util/modal/