---
deployment:
  tasks:
    - /bin/cp js/mainCtrl.js /home/ttsmcomm/public_html/js/
    
    - /bin/cp html/products/camera/EN_comet6.html /home/ttsmcomm/public_html/html/products/camera/
    - /bin/cp html/products/camera/EN_cometL3d2Base.html /home/ttsmcomm/public_html/html/products/camera/
    - /bin/cp html/products/camera/EN_cometL3d2Standard.html /home/ttsmcomm/public_html/html/products/camera/
    - /bin/cp html/products/camera/ES_comet6.html /home/ttsmcomm/public_html/html/products/camera/
    - /bin/cp html/products/camera/ES_cometL3d2Base.html /home/ttsmcomm/public_html/html/products/camera/
    - /bin/cp html/products/camera/ES_cometL3d2Standard.html /home/ttsmcomm/public_html/html/products/camera/
    - /bin/cp html/products/cmm/EN_laymaticSncFSystem.html /home/ttsmcomm/public_html/html/products/cmm/
    - /bin/cp html/products/cmm/EN_laymaticSncJSystem.html /home/ttsmcomm/public_html/html/products/cmm/
    - /bin/cp html/products/cmm/EN_layoutMachineAModel.html /home/ttsmcomm/public_html/html/products/cmm/
    - /bin/cp html/products/cmm/EN_layoutMachineEModel.html /home/ttsmcomm/public_html/html/products/cmm/
    - /bin/cp html/products/cmm/EN_layoutMachineFModel.html /home/ttsmcomm/public_html/html/products/cmm/
    - /bin/cp html/products/cmm/EN_layoutMachineGModel.html /home/ttsmcomm/public_html/html/products/cmm/
    - /bin/cp html/products/cmm/EN_layoutMachineJModel.html /home/ttsmcomm/public_html/html/products/cmm/
    - /bin/cp html/products/cmm/EN_layoutMachineMiniModel.html /home/ttsmcomm/public_html/html/products/cmm/
    - /bin/cp html/products/cmm/ES_laymaticSncFSystem.html /home/ttsmcomm/public_html/html/products/cmm/
    - /bin/cp html/products/cmm/ES_laymaticSncJSystem.html /home/ttsmcomm/public_html/html/products/cmm/
    - /bin/cp html/products/cmm/ES_layoutMachineAModel.html /home/ttsmcomm/public_html/html/products/cmm/
    - /bin/cp html/products/cmm/ES_layoutMachineEModel.html /home/ttsmcomm/public_html/html/products/cmm/
    - /bin/cp html/products/cmm/ES_layoutMachineFModel.html /home/ttsmcomm/public_html/html/products/cmm/
    - /bin/cp html/products/cmm/ES_layoutMachineGModel.html /home/ttsmcomm/public_html/html/products/cmm/
    - /bin/cp html/products/cmm/ES_layoutMachineJModel.html /home/ttsmcomm/public_html/html/products/cmm/
    - /bin/cp html/products/cmm/ES_layoutMachineMiniModel.html /home/ttsmcomm/public_html/html/products/cmm/
    - /bin/cp html/products/laser/EN_leicaAbsoluteTrackerAt403.html /home/ttsmcomm/public_html/html/products/laser/
    - /bin/cp html/products/laser/EN_leicaAbsoluteTrackerAt930.html /home/ttsmcomm/public_html/html/products/laser/
    - /bin/cp html/products/laser/EN_leicaAbsoluteTrackerAt960.html /home/ttsmcomm/public_html/html/products/laser/
    - /bin/cp html/products/laser/EN_leicaAbsoluteTrackerAts600.html /home/ttsmcomm/public_html/html/products/laser/
    - /bin/cp html/products/laser/ES_leicaAbsoluteTrackerAt403.html /home/ttsmcomm/public_html/html/products/laser/
    - /bin/cp html/products/laser/ES_leicaAbsoluteTrackerAt930.html /home/ttsmcomm/public_html/html/products/laser/
    - /bin/cp html/products/laser/ES_leicaAbsoluteTrackerAt960.html /home/ttsmcomm/public_html/html/products/laser/
    - /bin/cp html/products/laser/ES_leicaAbsoluteTrackerAts600.html /home/ttsmcomm/public_html/html/products/laser/
    - /bin/cp html/products/milling/EN_mill7System.html /home/ttsmcomm/public_html/html/products/milling/
    - /bin/cp html/products/milling/EN_portableMillSystem.html /home/ttsmcomm/public_html/html/products/milling/
    - /bin/cp html/products/milling/ES_mill7System.html /home/ttsmcomm/public_html/html/products/milling/
    - /bin/cp html/products/milling/ES_portableMillSystem.html /home/ttsmcomm/public_html/html/products/milling/
    - /bin/cp html/products/others/EN_dpaSystem.html /home/ttsmcomm/public_html/html/products/others/
    - /bin/cp html/products/others/EN_gapNinja.html /home/ttsmcomm/public_html/html/products/others/
    - /bin/cp html/products/others/EN_masterEye.html /home/ttsmcomm/public_html/html/products/others/
    - /bin/cp html/products/others/ES_dpaSystem.html /home/ttsmcomm/public_html/html/products/others/
    - /bin/cp html/products/others/ES_gapNinja.html /home/ttsmcomm/public_html/html/products/others/
    - /bin/cp html/products/others/ES_masterEye.html /home/ttsmcomm/public_html/html/products/others/
    - /bin/cp html/products/vectoron/EN_apiScan.html /home/ttsmcomm/public_html/html/products/vectoron/
    - /bin/cp html/products/vectoron/EN_raptorEye.html /home/ttsmcomm/public_html/html/products/vectoron/
    - /bin/cp html/products/vectoron/EN_raptorEye2.html /home/ttsmcomm/public_html/html/products/vectoron/
    - /bin/cp html/products/vectoron/EN_vectoronV6C.html /home/ttsmcomm/public_html/html/products/vectoron/
    - /bin/cp html/products/vectoron/EN_vectoronV6MII.html /home/ttsmcomm/public_html/html/products/vectoron/
    - /bin/cp html/products/vectoron/EN_vectoronVME300M.html /home/ttsmcomm/public_html/html/products/vectoron/
    - /bin/cp html/products/vectoron/ES_apiScan.html /home/ttsmcomm/public_html/html/products/vectoron/
    - /bin/cp html/products/vectoron/ES_raptorEye.html /home/ttsmcomm/public_html/html/products/vectoron/
    - /bin/cp html/products/vectoron/ES_raptorEye2.html /home/ttsmcomm/public_html/html/products/vectoron/
    - /bin/cp html/products/vectoron/ES_vectoronV6C.html /home/ttsmcomm/public_html/html/products/vectoron/
    - /bin/cp html/products/vectoron/ES_vectoronV6MII.html /home/ttsmcomm/public_html/html/products/vectoron/
    - /bin/cp html/products/vectoron/ES_vectoronVME300M.html /home/ttsmcomm/public_html/html/products/vectoron/
