---
deployment:
  tasks:
    - /bin/cp js/mainCtrl.js /home/ttsmcomm/public_html/js/
    
    - /bin/cp html/products/vectoron/EN_vectoronV7M.html /home/ttsmcomm/public_html/html/products/vectoron/
    - /bin/cp html/products/vectoron/ES_vectoronV7M.html /home/ttsmcomm/public_html/html/products/vectoron/