---
deployment:
  tasks:
    - /bin/cp EN_news.html /home/ttsmcomm/public_html/
    - /bin/cp ES_news.html /home/ttsmcomm/public_html/
    - /bin/cp EN_index.php /home/ttsmcomm/public_html/
    - /bin/cp ES_index.php /home/ttsmcomm/public_html/