---
deployment:
  tasks:
    - /bin/cp TTSM/system_v2/html/sharepoint/calibration_planner.php /home/ttsmcomm/public_html/TTSM/system_v2/html/sharepoint/
    - /bin/cp TTSM/system_v2/js/sharepoint/calibrationPlannerPageCtrl.php /home/ttsmcomm/public_html/TTSM/system_v2/js/sharepoint/
    - /bin/cp TTSM/system_v2/php/models/ServiceReminderModel.php /home/ttsmcomm/public_html/TTSM/system_v2/php/models/
    - /bin/cp TTSM/system_v2/php/resources/excel/ServiceReminderResource.php /home/ttsmcomm/public_html/TTSM/system_v2/php/resources/excel/
    - /bin/cp TTSM/system_v2/php/services/ServiceReminderService.php /home/ttsmcomm/public_html/TTSM/system_v2/php/services/
