---
deployment:
  tasks:
    - /bin/cp html/products/software/EN_spGauge.html /home/ttsmcomm/public_html/html/products/software/
    - /bin/cp html/products/software/ES_spGauge.html /home/ttsmcomm/public_html/html/products/software/
