---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ttsmcomm/public_html/html/products/others/
    - /bin/cp html/products/others/EN_mainOthers.html $DEPLOYPATH
    - /bin/cp html/products/others/ES_mainOthers.html $DEPLOYPATH