---
deployment:
  tasks:
    - /bin/cp EN_solutions.html /home/ttsmcomm/public_html/
    - /bin/cp ES_solutions.html /home/ttsmcomm/public_html/
    - /bin/cp html/solutions/* /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/link/* /home/ttsmcomm/public_html/html/solutions/link/
    
   