---
deployment:
  tasks:
    - /bin/cp EN_solutions.html /home/ttsmcomm/public_html/
    - /bin/cp ES_solutions.html /home/ttsmcomm/public_html/
    
    - /bin/cp html/solutions/ES_3DmagicREGALISSoftwareThatAnybody.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_AlignmentOfLargeObjects.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_AssemblyAssistMeasuringSolution.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_AutomatedAssemblyOfLarge.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_AutomatedManufacturingAndProduction.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_AutomatedMeasurementAndInspection.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_AutomaticMeasuringSolutionAutomatic.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_AutomaticMeasuringSolutionIn.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_AutomationOfMeasurementWork.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_DefectiveProductsPredictionBy.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_DesignModelReverseSolution.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_DigitizationOfQualityInspection.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_HighPrecisionMoldCopy.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_ImprovingProductQualityAnd.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_ImprovingTheQualityOf.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_ManagementAndUtilizationOf.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_MeasuringDimensionsOfRelatively.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_MeasuringSolutionHousingInspection.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_MeasuringSolutionSupplyAssembly.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_MeasuringSolutionVehicleWhite.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_MeasuringTheEnginePosition.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_MeasuringTheWheelPosition.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_OptimizingClampWorkBefore.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_OptimizingParametersForPush.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_PostureMeasurementpositioningOfUnit.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_QualityEvaluationOf3D.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_RobotAccuracyImprovementSolution.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_SheetMetalDistortionAnd.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_VerifyingByComparingCAE.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_VirtualAssembly.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/ES_solutionsMenu.html /home/ttsmcomm/public_html/html/solutions/
    
    - /bin/cp html/solutions/EN_3DmagicREGALISSoftwareThatAnybody.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_AlignmentOfLargeObjects.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_AssemblyAssistMeasuringSolution.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_AutomatedAssemblyOfLarge.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_AutomatedManufacturingAndProduction.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_AutomatedMeasurementAndInspection.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_AutomaticMeasuringSolutionAutomatic.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_AutomaticMeasuringSolutionIn.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_AutomationOfMeasurementWork.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_DefectiveProductsPredictionBy.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_DesignModelReverseSolution.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_DigitizationOfQualityInspection.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_HighPrecisionMoldCopy.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_ImprovingProductQualityAnd.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_ImprovingTheQualityOf.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_ManagementAndUtilizationOf.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_MeasuringDimensionsOfRelatively.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_MeasuringSolutionHousingInspection.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_MeasuringSolutionSupplyAssembly.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_MeasuringSolutionVehicleWhite.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_MeasuringTheEnginePosition.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_MeasuringTheWheelPosition.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_OptimizingClampWorkBefore.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_OptimizingParametersForPush.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_PostureMeasurementpositioningOfUnit.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_QualityEvaluationOf3D.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_RobotAccuracyImprovementSolution.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_SheetMetalDistortionAnd.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_VerifyingByComparingCAE.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_VirtualAssembly.html /home/ttsmcomm/public_html/html/solutions/
    - /bin/cp html/solutions/EN_solutionsMenu.html /home/ttsmcomm/public_html/html/solutions/

    - /bin/cp html/solutions/link/ES_3DmagicREGALISSoftwareThatAnybody_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_AlignmentOfLargeObjects_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_AssemblyAssistMeasuringSolution_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_AutomatedAssemblyOfLarge_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_AutomatedManufacturingAndProduction_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_AutomatedMeasurementAndInspection_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_AutomaticMeasuringSolutionAutomatic_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_AutomaticMeasuringSolutionIn_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_AutomationOfMeasurementWork_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_DefectiveProductsPredictionBy_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_DesignModelReverseSolution_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_DigitizationOfQualityInspection_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_HighPrecisionMoldCopy_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_ImprovingProductQualityAnd_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_ImprovingTheQualityOf_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_ManagementAndUtilizationOf_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_MeasuringDimensionsOfRelatively_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_MeasuringSolutionHousingInspection_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_MeasuringSolutionSupplyAssembly_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_MeasuringSolutionVehicleWhite_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_MeasuringTheEnginePosition_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_MeasuringTheWheelPosition_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_OptimizingClampWorkBefore_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_OptimizingParametersForPush_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_PostureMeasurementpositioningOfUnit_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_QualityEvaluationOf3D_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_RobotAccuracyImprovementSolution_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_SheetMetalDistortionAnd_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_VerifyingByComparingCAE_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/ES_VirtualAssembly_link.html /home/ttsmcomm/public_html/html/solutions/link/
    
    - /bin/cp html/solutions/link/EN_3DmagicREGALISSoftwareThatAnybody_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_AlignmentOfLargeObjects_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_AssemblyAssistMeasuringSolution_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_AutomatedAssemblyOfLarge_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_AutomatedManufacturingAndProduction_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_AutomatedMeasurementAndInspection_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_AutomaticMeasuringSolutionAutomatic_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_AutomaticMeasuringSolutionIn_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_AutomationOfMeasurementWork_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_DefectiveProductsPredictionBy_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_DesignModelReverseSolution_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_DigitizationOfQualityInspection_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_HighPrecisionMoldCopy_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_ImprovingProductQualityAnd_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_ImprovingTheQualityOf_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_ManagementAndUtilizationOf_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_MeasuringDimensionsOfRelatively_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_MeasuringSolutionHousingInspection_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_MeasuringSolutionSupplyAssembly_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_MeasuringSolutionVehicleWhite_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_MeasuringTheEnginePosition_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_MeasuringTheWheelPosition_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_OptimizingClampWorkBefore_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_OptimizingParametersForPush_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_PostureMeasurementpositioningOfUnit_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_QualityEvaluationOf3D_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_RobotAccuracyImprovementSolution_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_SheetMetalDistortionAnd_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_VerifyingByComparingCAE_link.html /home/ttsmcomm/public_html/html/solutions/link/
    - /bin/cp html/solutions/link/EN_VirtualAssembly_link.html /home/ttsmcomm/public_html/html/solutions/link/